<?php

namespace AppBundle\Repository;

/**
 * CenzorWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CenzorWordRepository extends \Doctrine\ORM\EntityRepository
{
}
